[package]
name        = "kodi-rpc"
version     = "1.1.0"
edition     = "2021"
description = "Backend for the Kodi-RPC-cli project (Discord Rich Presence for Kodi)"
license     = "GPL-3.0-or-later"
repository  = "https://github.com/nattadasu/kodi-rpc"
keywords    = ["kodi", "discord", "rich-presence"]

[dependencies]
discord-rich-presence = "1.0"
serde_json            = "1.0"
log                   = "0.4"
url                   = "2.5"
chrono                = "0.4"
image                 = "0.25"
urlencoding           = "2.1"

[dependencies.serde]
features = ["derive"]
version  = "1.0"

[dependencies.reqwest]
default-features = false
features         = ["rustls-tls", "json", "blocking", "multipart"]
version          = "0.12"
