[package]
name         = "kodi-rpc-cli"
version      = "1.0.0"
edition      = "2021"
description  = "Displays the content you're currently watching on Kodi in Discord!"
license      = "GPL-3.0-or-later"
repository   = "https://github.com/nattadasu/kodi-rpc"
keywords     = ["cli", "kodi", "discord", "rich-presence"]

exclude = [
    "scripts/*",
    ".github/*"
]

[[bin]]
name = "kodi-rpc"
path = "src/main.rs"

[features]
default = ["updates"]
updates = ["dep:reqwest"]

[dependencies]
colored               = "3.0"
retry                 = "2.1"
log                   = "0.4"
simple_logger         = "5.0"
time                  = "0.3"
serde_json            = "1.0"

[dependencies.kodi-rpc]
path = "../kodi-rpc"
version = "1.0.0"

[dependencies.clap]
features = ["derive"]
version  = "4.5"

[dependencies.reqwest]
default-features = false
features = ["rustls-tls", "json", "blocking"]
version  = "0.12"
optional = true

[dependencies.serde]
features = ["derive"]
version  = "1.0"
