name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all --check

  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: x86_64-linux

      - name: Build
        run: cargo build --workspace --locked --release

      - name: Rename binary
        run: mv target/release/kodi-rpc target/release/kodi-rpc-${SHORT_SHA}-x86_64-linux

      - name: Run cargo test
        run: cargo test --all-features --locked

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ env.SHORT_SHA }}
          path: target/release/kodi-rpc-${{ env.SHORT_SHA }}-x86_64-linux

  ubuntu-arm32:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: armv7-unknown-linux-gnueabihf

      - name: Update apt and install ARM32 gcc
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: arm32-linux

      - name: Build for ARM32 Linux
        run: cargo build --target armv7-unknown-linux-gnueabihf --workspace --locked --release
        env:
          CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc

      - name: Rename binary
        run: mv target/armv7-unknown-linux-gnueabihf/release/kodi-rpc target/armv7-unknown-linux-gnueabihf/release/kodi-rpc-${SHORT_SHA}-arm32-linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm32-${{ env.SHORT_SHA }}
          path: target/armv7-unknown-linux-gnueabihf/release/kodi-rpc-${{ env.SHORT_SHA }}-arm32-linux

  ubuntu-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Update apt and install ARM64 gcc
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: arm64-linux

      - name: Build for ARM64 Linux
        run: cargo build --target aarch64-unknown-linux-gnu --workspace --locked --release
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc

      - name: Rename binary
        run: mv target/aarch64-unknown-linux-gnu/release/kodi-rpc target/aarch64-unknown-linux-gnu/release/kodi-rpc-${SHORT_SHA}-arm64-linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-${{ env.SHORT_SHA }}
          path: target/aarch64-unknown-linux-gnu/release/kodi-rpc-${{ env.SHORT_SHA }}-arm64-linux

  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set short SHA
        shell: bash
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: x86_64-windows

      - name: Build
        run: cargo build --workspace --locked --release

      - name: Run cargo test
        run: cargo test --all-features --locked

      - name: Rename binary
        shell: bash
        run: mv target/release/kodi-rpc.exe target/release/kodi-rpc-${{ env.SHORT_SHA }}.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ env.SHORT_SHA }}
          path: target/release/kodi-rpc-${{ env.SHORT_SHA }}.exe

  macos-x86_64:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: x86_64-macos

      - name: Build for x86_64 macOS
        run: cargo build --target x86_64-apple-darwin --workspace --locked --release

      - name: Rename binary
        run: mv target/x86_64-apple-darwin/release/kodi-rpc target/x86_64-apple-darwin/release/kodi-rpc-${SHORT_SHA}-x86_64-darwin

      - name: Run cargo test
        run: cargo test --all-features --locked

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-x86_64-${{ env.SHORT_SHA }}
          path: target/x86_64-apple-darwin/release/kodi-rpc-${{ env.SHORT_SHA }}-x86_64-darwin

  macos-arm64:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: arm64-macos

      - name: Build for arm64 macOS
        run: cargo build --target aarch64-apple-darwin --workspace --locked --release

      - name: Rename binary
        run: mv target/aarch64-apple-darwin/release/kodi-rpc target/aarch64-apple-darwin/release/kodi-rpc-${SHORT_SHA}-arm64-darwin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-${{ env.SHORT_SHA }}
          path: target/aarch64-apple-darwin/release/kodi-rpc-${{ env.SHORT_SHA }}-arm64-darwin
